[Settings]
ID = "QA-I"
[build]
  # This will be your default build command
  base = "client/"
  command = "npm run build"
  publish = "client/dist"

#[[redirects]]
#  from = "/"
#  to = "/index.html"
#  status = 200
#  force = true

#[[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 301
#  force = true
  
[[redirects]]
  from = "/:page"
  to = "/index.html"
  status = 200
  force = true
